--------------------------------------------------------
--  File created - Wednesday-August-16-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "USSD"."CUSTOMERS" 
   (	"CUS_ID" NUMBER(5,0), 
	"NAME" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(6 BYTE), 
	"TYPE" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into USSD.CUSTOMERS
SET DEFINE OFF;
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (111,'Sadia','ACTIVE','PERSONAL');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (112,'Sanzid','ACTIVE','PERSONAL');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (113,'Arif','LOCKED','PERSONAL');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (114,'Radoan','ACTIVE','PERSONAL');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (115,'Tamim','ACTIVE','PERSONAL');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (116,'Urmi','FROZEN','PERSONAL');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (117,'Merchant1','ACTIVE','MERCHANT');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (118,'Merchant2','ACTIVE','MERCHANT');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (119,'Merchant3','ACTIVE','MERCHANT');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (120,'Merchant4','FROZEN','MERCHANT');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (121,'Bank1','ACTIVE','BANK');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (122,'Bank2','ACTIVE','BANK');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (123,'Bank3','ACTIVE','BANK');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (124,'Bank4','ACTIVE','BANK');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (125,'Biller1','ACTIVE','BILLER');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (126,'Biller2','ACTIVE','BILLER');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (127,'Biller3','FROZEN','BILLER');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (128,'Biller4','ACTIVE','BILLER');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (129,'Agent1','ACTIVE','AGENT');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (130,'Agent2','ACTIVE','AGENT');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (131,'Agent3','ACTIVE','AGENT');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (132,'Agent4','FROZEN','AGENT');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (134,'AIRTEL_PREPAID','ACTIVE','RECHARGE');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (137,'GRAMEENPHONE_PREPAID','ACTIVE','RECHARGE');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (135,'ROBI_PREPAID','ACTIVE','RECHARGE');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (133,'TELETALK_PREPAID','ACTIVE','RECHARGE');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (136,'BANGLALINK_PREPAID','ACTIVE','RECHARGE');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (138,'TELETALK_POSTPAID','ACTIVE','RECHARGE');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (139,'AIRTEL_POSTPAID','ACTIVE','RECHARGE');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (140,'ROBI_POSTPAID','ACTIVE','RECHARGE');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (141,'BANGLALINK_POSTPAID','ACTIVE','RECHARGE');
Insert into USSD.CUSTOMERS (CUS_ID,NAME,STATUS,TYPE) values (142,'GRAMEENPHONE_POSTPAID','ACTIVE','RECHARGE');
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "USSD"."CUSTOMERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "USSD"."CUSTOMERS" MODIFY ("STATUS" NOT NULL ENABLE);
