--------------------------------------------------------
--  File created - Wednesday-August-16-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MENU_ROUTES
--------------------------------------------------------

  CREATE TABLE "USSD"."MENU_ROUTES" 
   (	"ACCOUNT_TYPE" VARCHAR2(20 BYTE), 
	"PREV_RESPONSE" VARCHAR2(20 BYTE), 
	"NEXT_RESPONSE" VARCHAR2(20 BYTE), 
	"UINPUT" VARCHAR2(20 BYTE), 
	"SERVICE_ID" VARCHAR2(20 BYTE) DEFAULT 'none'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into USSD.MENU_ROUTES
SET DEFINE OFF;
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','1','18','8','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','18','181','1','pin_forgot');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','18','182','2','pin_change');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','182','182X','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','182X','182XX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','182XX','182XXX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','1','12','2','trns_send');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','12','12X','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','-1','1','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','1','15','5','trns_bill');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','15','15X','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','15X','15XX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','15XX','15XXX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','12X','12XX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','12XX','12XXX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','12XXX','12XXXX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','1','13','3','trns_recharge');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','13','13X','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','13XXX','13XXXX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','13XXXX','13XXXXX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','13X','13XX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','13XX','13XXX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','1','11','1','trns_cout');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','11','11X','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','11X','11XX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','11XX','11XXX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','1','14','4','trns_pay');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','14','14X','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','14X','14XX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','14XX','14XXX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','14XXX','14XXXX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','1','16','6','trns_emi');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','16','16X','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','16X','16XX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','16XX','16XXX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','16XXX','16XXXX','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','1','17','7','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','171','171X','-1','none');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','17','173','3','info_helpline');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','17','171','1','info_balance');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','17','172','2','info_statement');
Insert into USSD.MENU_ROUTES (ACCOUNT_TYPE,PREV_RESPONSE,NEXT_RESPONSE,UINPUT,SERVICE_ID) values ('PERSONAL','172','172X','-1','none');
--------------------------------------------------------
--  Constraints for Table MENU_ROUTES
--------------------------------------------------------

  ALTER TABLE "USSD"."MENU_ROUTES" MODIFY ("ACCOUNT_TYPE" NOT NULL ENABLE);
